# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('callback', models.CharField(max_length=256)),
                ('esn', models.CharField(max_length=16)),
                ('user', models.CharField(default='anon', max_length=16)),
                ('account', models.CharField(max_length=16)),
                ('result', models.UUIDField(null=True)),
            ],
        ),
    ]
